/**
 * utils/testResultPdf.js
 * ─────────────────────────────────────────────────────────────────────────────
 * Builds the per-student test-result PDF emailed immediately once an attempt
 * is evaluated (MCQ: auto, the moment it's submitted; Descriptive: the
 * moment an admin finishes grading it). Reuses the same table primitive as
 * every other report PDF in the app for a consistent look.
 * ─────────────────────────────────────────────────────────────────────────────
 */

const { drawTable, pctColor } = require("./attendanceReportFormat");

function buildTestResultPdf(doc, report) {
  const { test, student, attempt } = report;
  const pct = attempt.maxMarks > 0 ? Math.round((attempt.marksAwarded / attempt.maxMarks) * 100) : 0;

  doc.font("Helvetica-Bold").fontSize(20).fillColor("#1f2937").text("Test Result");
  doc.fillColor("black");
  doc.font("Helvetica").fontSize(11).text(test.title);
  doc.moveDown(0.6);

  doc.font("Helvetica-Bold").fontSize(12).text(student.name);
  doc.font("Helvetica").fontSize(10).fillColor("#4b5563");
  const metaParts = [
    student.admissionNumber ? `Roll No: ${student.admissionNumber}` : null,
    student.grade ? `Grade: ${student.grade}` : null,
    student.batch ? `Batch: ${student.batch}` : null,
  ].filter(Boolean);
  if (metaParts.length) doc.text(metaParts.join("   |   "));
  doc.fillColor("black");
  doc.moveDown(1);

  doc.font("Helvetica-Bold").fontSize(12).text("Score");
  doc.font("Helvetica").fontSize(11);
  doc.text(`Test type: ${test.type === "mcq" ? "Multiple Choice" : "Descriptive"}`);
  doc.text(`Marks obtained: ${attempt.marksAwarded} / ${attempt.maxMarks}`);
  doc.fillColor(pctColor(pct)).text(`Percentage: ${pct}%`).fillColor("black");
  doc.text(`Submitted: ${new Date(attempt.submittedAt).toLocaleString("en-IN")}`);
  if (attempt.autoSubmitted) doc.font("Helvetica-Oblique").fontSize(9).fillColor("#9ca3af").text("(Auto-submitted when the test's time expired)").fillColor("black").font("Helvetica");
  doc.moveDown(1);

  if (test.type === "mcq" && Array.isArray(report.questions)) {
    doc.font("Helvetica-Bold").fontSize(12).text("Question-wise breakdown");
    doc.moveDown(0.3);
    drawTable(doc, {
      headers: ["#", "Your answer", "Correct answer", "Result", "Marks"],
      rows: report.questions.map((q, i) => [
        String(i + 1),
        q.selectedOption ? q.selectedOption.toUpperCase() : "-",
        q.correctOption.toUpperCase(),
        q.isCorrect ? "Correct" : "Incorrect",
        `${q.marksAwarded}/${q.marks}`,
      ]),
      colWidths: [30, 100, 110, 100, 80],
    });
  } else if (test.type === "descriptive" && attempt.evaluatorFeedback) {
    doc.font("Helvetica-Bold").fontSize(12).text("Evaluator's feedback");
    doc.font("Helvetica").fontSize(11).text(attempt.evaluatorFeedback);
  }

  doc.moveDown(1.5);
  doc.font("Helvetica").fontSize(9).fillColor("#9ca3af")
    .text("This is an automated report generated by the Chemistry@OCTET LMS.", { align: "center" });
  doc.fillColor("black");
}

module.exports = { buildTestResultPdf };
