# fly.toml app configuration file generated for api-satin-leaf-209 on 2026-06-12T00:57:45+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'api-satin-leaf-209'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
